version: "3.3"
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  cronlock:
    image: bernardmcmanus/docker-cronlock
    depends_on:
      - redis
    volumes:
      - ./cronlock.conf:/etc/cronlock.conf
      - ./init:/docker-cronlock-init.d
      - ./crontab:/etc/crontab